### ISSUE TITLE
Pinto Server takes an eternity to process packets

### ISSUE THREAD

**Issue by matthilde** [PintoIM/PintoServer#1] opened 2023-05-03 06:46 UTC
OS: Windows 10 x86-64
Java version: OpenJDK 18

Problem: Pinto Server takes an eternity to process packets and makes it essentially impossible to log in or register.
![image](https://user-images.githubusercontent.com/21009482/235848131-0f3a9d06-e060-40b6-8fec-a72b17b0fa66.png)

**Comment by vlOd2** [comment] 2023-05-03 06:49
This goes into the category of current networking being janky
It will be fixed along side the other networking issues

**Comment by vlOd2** [comment] 2023-05-08 07:30
Not enough details, could not reproduce this issue

**Closed as not planned by vlOd2** 2023-05-08 07:30 UTC
